spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASS}

google.application.credentials=${GOOGLE_APPLICATION_CREDENTIALS}

object-storage.provider=s3

spring.jpa.hibernate.ddl-auto=validate

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
notificaciones.email.remitente=${MAIL_FROM}
