spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASS}

google.application.credentials=${GOOGLE_APPLICATION_CREDENTIALS}

object-storage.provider=s3

spring.jpa.hibernate.ddl-auto=validate