spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/backend}
spring.datasource.username=${DATASOURCE_USER:root_dev}
spring.datasource.password=${DATASOURCE_PASS:root_dev_pass}

google.application.credentials=${GOOGLE_APPLICATION_CREDENTIALS}

object-storage.local-path=./uploads
object-storage.provider=local