spring.application.name=backend

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASS}

google.application.credentials=${GOOGLE_APPLICATION_CREDENTIALS}

# TODO: add Springboot Security credentials

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Loggea instrucciones de SQL en la consola
spring.jpa.show-sql=true

# Hacer queries en dialecto de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
