spring.application.name=backend

# Settings de https://medium.com/@AlexanderObregon/using-spring-boot-with-postgresql-for-data-persistence-49e843ab46fc
spring.datasource.url=jdbc:postgresql://localhost:5432/mza-agrotours-bd?options=-c%20timezone%3DAmerica%2FArgentina%2FBuenos_Aires

spring.datasource.username=root_dev
spring.datasource.password=root_dev_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


# Loggea instrucciones de SQL en la consola
spring.jpa.show-sql=true

# Hacer queries en dialecto de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
