package com.mza_agrotours.backend.enums.outbox;

public enum TipoOperacion {
    ELIMINAR_USUARIO,
    AGREGAR_MIEMBRO_ESTABLECIMIENTO,
    QUITAR_MIEMBRO_ESTABLECIMIENTO,
    QUITAR_ESTABLECIMIENTO,
    QUITAR_USUARIO_CHAT,
    QUITAR_ACTIVIDAD_CHAT
}
